version: '3.1'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: nomad-io
      MYSQL_USER: cslee0034
      MYSQL_PASSWORD: 1234
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    command: redis-server --requirepass 1234
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    environment:
      REDIS_PASSWORD: 1234

volumes:
  mysql_data:
  redis_data:
