version: '3.1'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: fastdeal
      MYSQL_USER: cslee0034
      MYSQL_PASSWORD: 1234
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  # 캐싱 Redis
  redis_cache:
    image: redis:latest
    command: redis-server --requirepass 1234
    ports:
      - '6379:6379'
    volumes:
      - redis_cache_data:/data
    environment:
      REDIS_PASSWORD: 1234

  # 락킹 Redis
  redis_lock:
    image: redis:latest
    command: redis-server --requirepass 1234
    ports:
      - '6380:6379'
    volumes:
      - redis_lock_data:/data
    environment:
      REDIS_PASSWORD: 1234

  # 큐 Redis
  redis_queue:
    image: redis:latest
    command: redis-server --requirepass 1234
    ports:
      - '6381:6379'
    volumes:
      - redis_queue_data:/data
    environment:
      REDIS_PASSWORD: 1234

volumes:
  mysql_data:
  redis_cache_data:
  redis_lock_data:
  redis_queue_data:
