version: '3.1'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${RDB_PASSWORD}
      MYSQL_DATABASE: ${RDB_DATABASE}
      MYSQL_USER: ${RDB_USERNAME}
      MYSQL_PASSWORD: ${RDB_PASSWORD}
    ports:
      - '${RDB_PORT}:${RDB_PORT}'
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    command: redis-server --requirepass ${CACHE_PASSWORD}
    ports:
      - '${CACHE_PORT}:${CACHE_PORT}'
    volumes:
      - redis_data:/data
    environment:
      REDIS_PASSWORD: ${CACHE_PASSWORD}

volumes:
  mysql_data:
  redis_data:
